# Generated by Django 3.2.12 on 2022-03-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_auto_20220310_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='imageName',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='name',
            new_name='layerName',
        ),
        migrations.AlterField(
            model_name='image',
            name='layer',
            field=models.ForeignKey(default=814, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generators.layer'),
        ),
    ]
